# Generated by Django 5.2.8 on 2025-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('img', models.CharField(blank=True, help_text='Main image URL or path', max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('link', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoicerecord',
            options={},
        ),
    ]
